server:
  port: 4000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-URL:http://localhost:8761/eureka}
