spring:
  data:
    mongodb:
      uri: ${DB_URL}
  config:
    import: optional:file:.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  file:
    path: .
    name: app.log
server:
  port: 8081
