spring:
  data:
    mongodb:
      uri: ${DB_URL}
  config:
    import: optional:file:.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  file:
    path: .
    name: app.log
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-URL:http://localhost:8761/eureka}
server:
  port: 8081
grpc:
  port: 7777
  enable-reflection: true
