spring:
  application:
    name: private-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    consumer:
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: *
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
logging:
  file:
    path: ./private_service/
    name: app.log

server:
  port: 8082

feign:
  hystrix:
    enabled: true
