#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#
#ribbon:
#  ReadTimeout: 20000
#  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    media-service:
      path: /media/**
      url: http://localhost:8081/
#      serviceId: media-service
#      stripPrefix: false
#      sensitiveHeaders:

    private-service:
      path: /private/**
      url: http://localhost:8082/
      serviceId: private-service
      stripPrefix: false
      sensitiveHeaders:
#
#    statistics-service:
#        path: /statistics/**
#        serviceId: statistics-service
#        stripPrefix: false
#        sensitiveHeaders:
#
#    notification-service:
#        path: /notifications/**
#        serviceId: notification-service
#        stripPrefix: false
#        sensitiveHeaders:

server:
  port: 4000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true